[package]
name = "u1"
version = "0.0.1"
edition = "2024"
authors = ["bootylickr <bootyman@booty.com>"]
description = "WomanPussyLick"
license = "PantyStink"  

[dependencies]
cfonts = "1.3.0"
rand = "0.9.2"
yansi = "1.0.1"
